config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/trash_em'
  get 'home/trash_em_all'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def trash_em
    @trash_em = List.where(:completed => true).destroy_all
    redirect_to root_url, notice: 'All completed items were successfully deleted.'
  end

  def trash_em_all
    @trash_em_all = List.all.destroy_all
    redirect_to root_url, notice: 'All items were successfully deleted.'
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoBootstrap</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "lists/navbar" %>
    <div class="container">
      <%= render "flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_flash.html.erb
<br />
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-check form-check-inline">
    <%= form.label :completed, class: 'form-check-label' %>
    <%= form.check_box :completed, class: 'form-check-input' %>
  </div>

  <div class="form-group">
    <%= form.submit "Update", class: 'form-control btn btn-outline-success' %>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex">
    <%= form.text_field :description, class: "form-control me-2", placeholder: 'Add new todo', aria: {label: 'Add new todo'} %>
    <%= form.submit "Add", class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <td class="col-9 <%= list.completed ? 'striker' : '' %>">
    <%= link_to list.description, edit_list_path(list), class: list.completed ? 'text-white' : 'text-dark' %>
    <% list.description %>
  </td>

</div>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Todo List", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <%= render "form_index", list: @list %>
    </div>
  </div>
</nav>

app/views/lists/edit.html.erb
<%# <h1>Edit Todo Item</h1> %>

<center>
  <div class="card col-6">
      <h1 class="card-header">Edit Todo</h5>
    <div class="card-body">
      <%= render "form", list: @list %>
    </div>
    <div class="card-footer">
      <% link_to "Show this list", @list %>
      <%= link_to "Back to lists", root_path %>
    </div>
  </div>
</center>

app/views/lists/index.html.erb
<div id="lists">
  <table class="table table-bordered">
  <tbody>
    <% @lists.each do |list| %>
      <tr class="<%= list.completed ? 'bg-secondary text-light' : 'text-dark' %>">
        <%= render list %>
        <td>
          <% if list.completed %>
            <%= form_for (list) do |f| %>
              <%= f.text_field :description, type: "hidden" %>
              <%= f.check_box :completed, :checked => false, :style => "visibility: hidden" %>
              <%= f.submit "Uncheck", class: 'btn btn-outline-light btn-sm' %>
            <% end %>
          <% else %>
            <%= form_for (list) do |f| %>
              <%= f.text_field :description, type: "hidden" %>
              <%= f.check_box :completed, :checked => true, :style => "visibility: hidden" %>
              <%= f.submit "Cross Off", class: 'btn btn-outline-secondary btn-sm' %>
            <% end %>
          <% end %>
        </td>
        <td>
          <center><%= button_to "Delete", list, method: :delete, class: 'btn btn-outline-danger', data: {confirm: 'Are you sure?' } %></center>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

<% link_to "Add todo item", new_list_path, class: 'btn btn-secondary text-white' %>

<br />
<br />

<center>
  <%= link_to 'Delete Completed Items', home_trash_em_path, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Delete All Items', home_trash_em_all_path, data: { confirm: 'Are you sure?' } %>
</center>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", root_path %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list %>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", root_path %>

  <%= button_to "Destroy this list", @list, method: :delete %>
</div>